Python 2.7:
    script:
    - export PY_EXE=python2.7
    - virtualenv env
    - source env/bin/activate
    - pip install -r requirements.txt
    - export DISPLAY=:10
    - python manage.py test
    except:
    - tags