Python 2.7:
    script:
    - export PY_EXE=python2.7
    - sudo Xvfb :10 -ac
    - export DISPLAY=:10
    - virtualenv env
    - source env/bin/activate
    - pip install -r requirements.txt
    - python manage.py test
    tags:
    - python2.7
    except:
    - tags